import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import List, Optional
from backend.config.settings import get_settings

settings = get_settings()


class EmailService:
    """Service for sending email alerts via SMTP (Gmail)."""
    
    def __init__(self):
        self.host = settings.EMAIL_HOST
        self.port = settings.EMAIL_PORT
        self.user = settings.EMAIL_USER
        self.password = settings.EMAIL_APP_PASSWORD
        self.recipients = settings.EMAIL_RECIPIENTS
        
    def _get_risk_category(self, risk_score: float) -> str:
        """Determine risk category from score."""
        if risk_score < 30:
            return "Low"
        elif risk_score < 60:
            return "Medium"
        elif risk_score < 85:
            return "High"
        else:
            return "Critical"
    
    def _create_email_body(self, risk_score: float, risk_category: str, is_manual: bool = False) -> str:
        """Create email body content."""
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        manual_note = "\n\nNote: This alert was manually triggered by an administrator." if is_manual else ""
        
        body = f"""
High probability of protest or violent activity detected.

Timestamp: {timestamp}
Risk Score: {risk_score:.1f}/100
Risk Category: {risk_category}

{manual_note}

---
This alert was generated by the National Public Discourse Intelligence System (Demo)
        """.strip()
        
        return body
    
    def send_alert(self, risk_score: float, is_manual: bool = False) -> bool:
        """
        Send email alert to configured recipients.
        
        Args:
            risk_score: Current escalation risk score (0-100)
            is_manual: Whether this is a manually triggered alert
            
        Returns:
            True if email sent successfully, False otherwise
        """
        try:
            if not all([self.host, self.port, self.user, self.password, self.recipients]):
                print("Email configuration incomplete. Skipping email send.")
                return False
            
            risk_category = self._get_risk_category(risk_score)
            
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.user
            msg['To'] = ', '.join(self.recipients)
            msg['Subject'] = "[ALERT] High Risk Detected – NIS System"
            
            body = self._create_email_body(risk_score, risk_category, is_manual)
            msg.attach(MIMEText(body, 'plain'))
            
            # Send email via SMTP
            with smtplib.SMTP(self.host, self.port) as server:
                server.starttls()
                server.login(self.user, self.password)
                server.send_message(msg)
            
            print(f"Email alert sent successfully. Risk Score: {risk_score:.1f}")
            return True
            
        except Exception as e:
            print(f"Error sending email alert: {e}")
            return False
    
    def send_test_email(self) -> bool:
        """Send a test email to verify configuration."""
        try:
            if not all([self.host, self.port, self.user, self.password, self.recipients]):
                return False
            
            msg = MIMEMultipart()
            msg['From'] = self.user
            msg['To'] = ', '.join(self.recipients)
            msg['Subject'] = "[TEST] NIS Email Alert System Test"
            
            body = f"""
This is a test email from the National Public Discourse Intelligence System.

Timestamp: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}

If you received this email, the email alert system is configured correctly.

---
This alert was generated by the National Public Discourse Intelligence System (Demo)
            """.strip()
            
            msg.attach(MIMEText(body, 'plain'))
            
            with smtplib.SMTP(self.host, self.port) as server:
                server.starttls()
                server.login(self.user, self.password)
                server.send_message(msg)
            
            print("Test email sent successfully.")
            return True
            
        except Exception as e:
            print(f"Error sending test email: {e}")
            return False


# Singleton instance
_email_service: Optional[EmailService] = None

def get_email_service() -> EmailService:
    """Get singleton email service instance."""
    global _email_service
    if _email_service is None:
        _email_service = EmailService()
    return _email_service
